@baseUrl = http://localhost:3000

### Sign up
POST {{baseUrl}}/api/auth/sign-up/email
Content-Type: application/json
Origin: {{baseUrl}}

{
  "email": "user1@example.com",
  "password": "secret123",
  "name": "John"
}

### Sign in
# @name signIn
POST {{baseUrl}}/api/auth/sign-in/email
Content-Type: application/json
Origin: {{baseUrl}}

{
  "email": "user1@example.com",
  "password": "secret123"
}

### Get current user
GET {{baseUrl}}/users/me
Authorization: Bearer {{signIn.response.body.token}}
